### ISSUE TITLE
Timing 8-10

### ISSUE THREAD

**Issue by jniezink** [tianevitt/tianzes-gauntlight-extras#2]
Hi,

Not really an issue, more out of interest. I've seen your add-on and I like it very much. I am going to use it, but I expect that my group will clean out lvls 5 & 6 quite easily. Do you have a planned timeline for levels 8-10? As far as I can see there are no tight connections now if I start using it, but I am not completely sure :)

**Comment by tianevitt** [comment]
Hey there; I'll keep this "issue" open as an incentive. 

I am glad you are enjoying it. I currently have my group in level 10, and have been building out the remaining levels as I go along. I have my scene for the Farm level pretty much done, I just need to put all my "extras" in a clean copy of the scene, so I will focus my next update on just getting that out the door.

**Comment by tianevitt** [comment]
Level 8 is released, and Foundry has been updated.
