### ISSUE TITLE
Typo on Journal Entry

### ISSUE THREAD

**Issue by tatsumasagc** [tianevitt/tianzes-gauntlight-extras#8]
In the jornal entry, Lv7. Prison > The Roseguard and the Portal Ritual > Scene Setup, it states "Place Idriniliss Haunt in G04 Drill Field..." but the Drill field is G03.

**Comment by tianevitt** [comment]
Thanks!

**Comment by tianevitt** [comment]
Typo (along with some others) should be fixed. Thanks for the bug report.
